const QA_CHOICE_QUESTION_COST = 5;
const QA_SUBJECTIVE_QUESTION_COST = 10;
const QA_RECRUIT_TITLE_MAX_LENGTH = 50;

export {
  QA_CHOICE_QUESTION_COST,
  QA_RECRUIT_TITLE_MAX_LENGTH,
  QA_SUBJECTIVE_QUESTION_COST,
};
